parameters:
    autosuggest.service.class: 'SimpleGMapsBundle\Service\AutoSuggestService'

services:
    city_suggest:
        class: '%autosuggest.service.class%'
        arguments: ["%google_places_key%"]
